[platformio]
src_dir = firmware/BASE
default_envs = teensy41

[env:teensy41]
platform = platformio/teensy
board = teensy41
framework = arduino
monitor_speed = 115200

build_flags =
	-I firmware/BASE
	-I firmware/BASE/mission
	-I firmware/BASE/sensors
	-I firmware/BASE/control
	-I firmware/BASE/logging
	-I firmware/BASE/common

lib_deps =
	paulstoffregen/OneWire
	milesburton/DallasTemperature
